# Generated by Django 5.2.16 on 2026-07-16 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('current_status', models.CharField(max_length=50)),
                ('last_source', models.CharField(max_length=50)),
                ('last_event_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('event_timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['-event_timestamp', 'id'],
                'indexes': [models.Index(fields=['order', '-event_timestamp'], name='idx_event_order_ts')],
                'constraints': [models.UniqueConstraint(fields=('order', 'event_timestamp', 'source'), name='uniq_order_event_timestamp_source')],
            },
        ),
    ]
